### ISSUE TITLE
changing threshold for volume shifting causes error

### ISSUE THREAD

**Issue by dcanelhas** [mp3guy/Kintinuous#13]
Providing a non-default threshold for shifting the volume when running the program (option -t) may cause the configuration arguments to clearVolumeInX<<<grid, block>>> in tsdf_volume.cu to become invalid.

namely grid.x can sometimes be negative.

try
./Kintinuous -s 8 -v ../vocab.yml.gz -l ../loop.klg -ri -od -t 60

and wait about a minute into the sequence.

**Comment by mp3guy** [comment]
I guess as a stop gap you could put an abs around the remainder getting passed into the grid dimensions, but a shifting threshold on the order of 60 was something I rarely tried out in the past since it was suboptimal in terms of tracking and also latency spikes. I'm reluctant to commit a fix here because I don't have the time to ensure it doesn't break something else. But feel free to try it out yourself. 

For now I'll limit the shifting threshold between 1 and 16 inclusive, since I can't guarantee it works outside of that range (especially for code I wrote almost 5 years ago (!)).

**Comment by dcanelhas** [comment]
The fix doesn't seem to cause any other problems, as far as i can tell.
