### ISSUE TITLE
crash on dyson_lab.klg

### ISSUE THREAD

**Issue by dcanelhas** [mp3guy/Kintinuous#14]
Seems there is an issue when the trajectory is short relative to the size of the volume (just a guess). Running Kintinuous on the smaller-scale dataset of dyson_lab.klg (compared to loop) causes the following error:

Kintinuous: ~/Kintinuous/src/backend/Deformation.cpp:264: void Deformation::addCameraLoop(): Assertion `deformationGraph' failed.
Aborted (core dumped)

**Comment by mp3guy** [comment]
This is a known issue with particular volume sizes versus trajectory shapes. Basically the code is never entering this path; https://github.com/mp3guy/Kintinuous/blob/master/src/backend/Deformation.cpp#L482

You can try coerce it into doing so setting the pose sampling distance to something much lower with -dg 0.2 for example. But datasets like the dyson_lab.klg one are the reason I made ElasticFusion, because Kintinuous was just bad a very loopy comprehensive scanning type reconstructions!
